### ISSUE TITLE
Add support for embedding media (YouTube, Twitter, Vimeo, Instagram etc.)

### ISSUE THREAD

**Issue by demen1n** [yadenis/DCO-Comment-Attachment#1]
Hi! Please add support for embedding media in the comments from third-party services, such as instagram, YouTube, Twitter.

**Comment by yadenis** [comment]
Hello @qpixboss,
This is a good idea! I'll try to implement it for the first release.

**Comment by yadenis** [comment]
Hello @qpixboss,
Thank you for the idea, I will think about it in future releases, but for now, you can try using [oEmbed in Comments](https://wordpress.org/plugins/oembed-in-comments/) plugin and insert links to YouTube, Vimeo, etc. directly in the Comment field.

**Comment by yadenis** [comment]
Resolved in 42d1b123a9a2333fa96fec4d4c6b5c3c7f40ed60.
