### ISSUE TITLE
Add Compatibility Mode with Comment Attachment plugin

### ISSUE THREAD

**Issue by yadenis** [yadenis/DCO-Comment-Attachment#13]
Link to plugin: https://wordpress.org/plugins/comment-attachment/

Add feature for use attachments attached in Comment Attachment plugin.

**Comment by fullsteamlabs** [comment]
The Comment Attachment plugin was recently removed from wordpress.org.

**Comment by yadenis** [comment]
@fullsteamlabs Thank you for notification!

The plugin is still not available for download. It looks like it is abandoned. If so, then the issue is no longer relevant.
