### ISSUE TITLE
Resize pictures and click-to-zoom

### ISSUE THREAD

**Issue by demen1n** [yadenis/DCO-Comment-Attachment#2]
Hi, Denis! Please, add in next release new feature for big images: resize pictures and click-to-zoom.

**Comment by yadenis** [comment]
Hi @qpixboss ,
I don't plan to implement a tool for resizing images, but I plan to add a setting to select the size of thumbnails specified in WordPress, theme and plugins used on the site.

> click-to-zoom

Many users implement it by using a third-party plugins and I think for a start we need to do some research to understand how to use it.
In any case, I think this is a topic for a separate issue.

**Comment by yadenis** [comment]
I've created a separate issue #4 for discuss click-to-zoom topic.

**Comment by yadenis** [comment]
Resolved in https://github.com/yadenis/DCO-Comment-Attachment/commit/fa84f4ff234b0447b77d6360d4d019e2fb23ebe4.

![image](https://user-images.githubusercontent.com/5316579/57092717-b0883200-6d14-11e9-93c7-5d9c8da96e8a.png)
