### ISSUE TITLE
Needs access controls

### ISSUE THREAD

**Issue by Synetech** [yadenis/DCO-Comment-Attachment#25]
This is a useful plugin, but without the ability to restrict uploading attachments to only users that are logged in it is too risky to use because anonymous users or bots could upload malware or a lot of files to fill up the disk.

Please add an "allow only logged-in users to post" feature.

(If you can also make it so that we can allow specific users, then that would be an extra bonus.)

**Comment by yadenis** [comment]
Hello @synetech,

Thank you for the idea. I added it to the list of future enhancements.

At the moment, you can restrict uploading attachments for anonymous users using this snippet:
```
if( ! is_user_logged_in() ) {
	add_filter( 'dco_ca_disable_attachment_field', '__return_true');
}
```

**Comment by yadenis** [comment]
The feature for restrict uploading attachments only to logged users avaliable at version 1.3.0.

An advanced feature with specific roles and users will most likely be implemented in the Pro version.
