### ISSUE TITLE
Transtion is not available for Chinese

### ISSUE THREAD

**Issue by Styunlen** [yadenis/DCO-Comment-Attachment#27]
It still shows in English

**Comment by yadenis** [comment]
Hello @Styunlen,

You can add translation to [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/dco-comment-attachment/stable/zh-cn/default/), then contact the Chinese Translation Team to approve your translation, and then you can use the plugin in Chinese.

An alternative is to translate locally using the [Loco Translate plugin](https://cn.wordpress.org/plugins/loco-translate/).

**Comment by yadenis** [comment]
Closing. Feel free to reopen this issue, or create a new one if you have another questions.
