### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by demen1n** [yadenis/DCO-Comment-Attachment#3]
Hello. May you add support for several files in comment?

**Comment by yadenis** [comment]
Hi @qpixboss 
Yes, I think about the feature to attach multiple files. Most likely this will be implemented in future releases.

**Comment by GeekDenCode** [comment]
Any news?

**Comment by NETBREDER** [comment]
Multiple files attachment would be great. Really nice plugin @yadenis! Keep it up.

**Comment by MikeWP** [comment]
Hello! Great plugin. Do you know when we can expect this feature?

**Comment by yadenis** [comment]
Multiple upload is available in DCO Comment Attachment since version 2.0.0.
