### ISSUE TITLE
Multiple files attachment

### ISSUE THREAD

**Issue by cbeltr2020** [yadenis/DCO-Comment-Attachment#31]
Hi Folks,

I have the following request which I hope you can take into consideration. It is not an issue but a feature enhancement. I am new to github, hence I do not know where else I could post this request.

The request is to have the ability to select and attach multiple files to a comment. At present, only one attachment can be added per comment.

Background of this request is that I am building a simple website for the students of a primary school in my daughters class. This is a simple site where their teachers can post an excercise and students can reply with a comment and attach an image. This can be very useful in these COVID times, to keep up with the school program.

Your plug in is very easy to use, however, I'd like to give them the ability to add multiple attachments, not only one. Is there an easy solution with your plugin? 

Thanks for your time and I hope you can take this enhancement into consideration.
Carlo

**Comment by yadenis** [comment]
Hello @cbeltr2020,

I'm sorry to be late with the reply.

Unfortunately, at the moment there is no way to upload multiple images in the plugin and there is no easy way to add this feature. But, for example, you can archive multiple images in one archive.

There is already a [similar issue](https://github.com/yadenis/DCO-Comment-Attachment/issues/3), so I close this one as a duplicate.

You can [subscribe it](https://github.com/yadenis/DCO-Comment-Attachment/issues/3) to stay tuned.
