### ISSUE TITLE
Feature request: Allow for comments with attachments to be put into the moderation queue

### ISSUE THREAD

**Issue by matthewmcvickar** [yadenis/DCO-Comment-Attachment#34]
There is currently no way in the admin to hold comments that have attachments in the moderation queue. This would be very useful!

**Comment by yadenis** [comment]
Hello @matthewmcvickar,

Thank you for the idea!

This feature was added in version 2.1.0.

**Comment by matthewmcvickar** [comment]
@yadenis That’s great! Thank you so much! :)
