### ISSUE TITLE
File upload restrictions

### ISSUE THREAD

**Issue by demen1n** [yadenis/DCO-Comment-Attachment#5]
Hi. The restrictions on uploading files such as type and size are not clear for users. Error messages are also not displayed if the file does not meet the requirements.
Can you add a description of restrictions and error messages if they are not met?

**Comment by yadenis** [comment]
I've added description of file upload restrictions and error messages.
![2019-04-30_072310](https://user-images.githubusercontent.com/5316579/56940744-e2cd4000-6b18-11e9-87c7-7ec7f699188e.jpg)
